name: Build uxptch (Windows x64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Locate Visual Studio and setup x64 environment
        shell: cmd
        run: |
          for /f "usebackq delims=" %%I in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set "VSROOT=%%I"
          if not defined VSROOT exit /b 1
          call "%VSROOT%\VC\Auxiliary\Build\vcvarsall.bat" x64
          if errorlevel 1 exit /b 1

      - name: Validate source file
        shell: cmd
        run: |
          if not exist "uxptch.cpp" exit /b 1

      - name: Build uxptch.exe
        shell: cmd
        run: |
          cl /nologo /EHsc /O2 /MD "uxptch.cpp" dbghelp.lib /Fe:uxptch.exe
          if errorlevel 1 exit /b 1

      - name: Upload artifact: exe
        uses: actions/upload-artifact@v4
        with:
          name: uxptch-win-x64-exe
          path: uxptch.exe
