name: Build Uxpatcher (MSVC)

on:
  push:
    paths:
      - 'uxptch.cpp'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'uxptch.cpp'
      - '.github/workflows/**'

jobs:
  build-windows:
    name: Build on Windows (x64)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Locate Visual Studio (vswhere) and show info
        shell: powershell
        run: |
          Write-Host "Buscando instalación de Visual Studio..."
          $vs = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          if (-not $vs) { throw "Visual Studio no encontrado en el runner." }
          Write-Host "Visual Studio encontrado en: $vs"
          Write-Host "VS version:"
          & "$vs\Common7\Tools\VsDevCmd.bat" -help | Select-Object -First 20

      - name: Build with MSVC (cl.exe)
        shell: powershell
        run: |
          # Preparar entorno de compilador para x64
          $vs = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          & "$vs\Common7\Tools\VsDevCmd.bat" -arch=amd64

          # Ajusta el nombre/ubicación si tu fuente no está en la raíz
          Write-Host "Compilando uxptch.cpp..."
          cl.exe /EHsc /std:c++17 /O2 uxptch.cpp Dbghelp.lib /Fe:uxptch.exe

          Write-Host "Contenido del directorio:"
          dir

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: uxptch-windows-x64
          path: uxptch.exe
