name: Build uxptch (MSVC x64 safe stub)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows-msvc:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Visual Studio Build Tools
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://aka.ms/vs/17/release/vs_BuildTools.exe" -OutFile vs_BuildTools.exe

      - name: Install Visual Studio Build Tools (VC + SDK)
        shell: powershell
        run: |
          Start-Process -FilePath .\vs_BuildTools.exe -ArgumentList @(
            "--quiet","--wait","--norestart","--nocache",
            "--installPath","C:\BuildTools",
            "--add","Microsoft.VisualStudio.Workload.VCTools",
            "--add","Microsoft.VisualStudio.Component.Windows10SDK.19041.x64",
            "--includeRecommended"
          ) -NoNewWindow -Wait

      - name: Setup x64 environment
        shell: cmd
        run: |
          call "C:\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
          if errorlevel 1 exit /b 1

      - name: Compile uxptch.exe with MSVC
        shell: cmd
        run: |
          cl /nologo /EHsc /O2 /MD uxptch.cpp /Fe:uxptch.exe
          if errorlevel 1 exit /b 1

      - name: Show produced file
        shell: cmd
        run: dir uxptch.exe
