name: Build uxptch (Windows x64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Visual Studio Build Tools
        shell: cmd
        run: |
          curl -Lo vs_BuildTools.exe https://aka.ms/vs/17/release/vs_BuildTools.exe
          vs_BuildTools.exe --quiet --wait --norestart --nocache --installPath C:\BuildTools --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.Windows10SDK.19041.x64 --includeRecommended

      - name: Setup x64 build environment
        shell: cmd
        run: |
          call "C:\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          if errorlevel 1 exit /b 1

      - name: Validate source file
        shell: cmd
        run: |
          if not exist "uxptch.cpp" exit /b 1

      - name: Build uxptch.exe
        shell: cmd
        run: |
          cl /nologo /EHsc /O2 /MD "uxptch.cpp" dbghelp.lib /Fe:uxptch.exe
          if errorlevel 1 exit /b 1
